<template>
  <div class="container mx-auto">
    <div
      class="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto overflow-x-hidden outline-none focus:outline-none"
    >
      <div class="relative my-6 mx-auto max-w-3xl">
        <div
          class="relative flex w-full flex-col rounded-lg border-0 bg-white shadow-lg outline-none focus:outline-none"
        >
          <div class="relative flex-auto p-6">
            <p class="my-4 text-lg leading-relaxed text-slate-500">
              {{ question }}
            </p>
          </div>

          <div
            class="flex items-center justify-end rounded-b border-t border-solid border-slate-200 p-6"
          >
            <button
              class="mr-1 mb-1 rounded border border-solid border-red-500 bg-transparent px-6 py-3 text-sm font-bold uppercase text-red-500 outline-none transition-all duration-150 ease-linear hover:bg-red-500 hover:text-white focus:outline-none active:bg-red-600"
              type="button"
              @click.prevent="close()"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="fixed inset-0 z-40 bg-black opacity-25"></div>
  </div>
</template>

<script setup lang="ts">
const question = ref()
const emit = defineEmits(['closeModal'])

function getQuestion() {
  return allQuestions[Math.floor(Math.random() * allQuestions.length)]
}

onMounted(() => {
  question.value = getQuestion()
})

function close() {
  emit('closeModal')
}

const allQuestions = [
  'Do you give money to homeless people/beggars? Why or why not?',
  'If you were given five million dollars to open a small museum, what kind of museum would you create?',
  'What obstacles would be included in the World’s most amazing obstacle course?',
  'What’s something common from your childhood that will seem strange to future generations?',
  'Do you ride motorcycles? Do you wear a helmet when bicycling or motorcycling? Is it the law where you live?',
  'One thing I use every day that I could probably live without is...',
  'On a typical month, how much is your long distance phone bill? Does that include international calls?',
  'In the past people were buried with the items they would need in the afterlife, what would you want buried with you so you could use it in the afterlife?',
  'What fashion trend makes you cringe or laugh every time you see it?',
  'Are you a gourmet - enjoying trying all sorts of international cuisine or do you prefer to eat the same basic food all the time?',
  'How many times during the year do you travel? How many times for business and how many pleasure vacations?',
  'Do you have a desire for a lot of land with your home? How much?',
  'What’s the most pleasant sounding accent?',
  'What weird potato chip flavor that doesn’t exist would you like to try?',
  'How many weeks each year can you take off from work?',
  'Do you decorate elaborately for holidays? Would you like to put up more decorations if you had the time/money?',
  'Describe your getting ready for work/getting ready for bed ritual.',
  'If you were given one thousand acres of land that you didn’t need to pay taxes on but couldn’t sell, what would you do with it?',
  'How many hours of TV do you watch in an average day? When do you turn the television on and when do you turn it off?',
  'What mythical creature do you wish actually existed?',
  'If I could go back in time, I would change _______ so that ______...',
  'What is your primary mode of transportation? Do you wish you had a different option?',
  "What's your favorite ice cream flavor?",
  'My favorite comfort food is...',
  'Do you tend to be punctual or are you usually late?',
  'What’s your good luck charm?',
  'Do you personally wash and wax your car? How often?',
  'Do you like a breeze blowing on you while you are asleep?',
  'Do you save up for a vacation or do you put it all on credit and pay it off as you can?',
  'How many hours a week do you usually spend taking care of your yard?',
  'If you were moving to another country, but could only pack one carry-on sized bag, what would you pack?',
  'What is the maximum length vacation you think you could take away from work without causing a problem? If you were retired or between jobs how long could you be away?',
  'Do you make your bed every day? Does it bother you if it is left unmade?',
  'What “old person” things do you do?',
  'What word do you always mispronounce?',
  'What is your favorite snack food? Dessert?',
  'What inconsequential super power would you like to have?',
  'Have you ever hired a gardener? Do you think they are a waste of money or money well spent?',
  'Do you get irritated when you have to wait in long lines? Will you wait 45 minutes to be seated in a restaurant?',
  'Where do you get most of the decorations for your home?',
  'My dream home would be...',
  'Do you enjoy debating others?',
  'What word is a lot of fun to say?',
  'What animal would be cutest if scaled down to the size of a cat?',
  'Have you seriously studied other faiths besides your own? If you are a Christian do you know what other denominations believe and teach?',
  'If you could make any three changes to our school systems, what would they be?',
  'How do you feel about going on weekend getaways?',
  'What product do you wish a company would make a “smart” version of?',
  "Do you enjoy experiencing different ways of life or do you usually find it frustrating that they don't do things as efficiently or like the way things are done back home?",
  'How often do you get sick? Is it a cold, flu or usually something else?',
  'Do you get your pets "fixed" or do you allow them to keep producing litters? What do you do with the babies?',
  'Do you fly as cheaply as possible or do you splurge for business or first class when going on vacation?',
  'What odd smell do you really enjoy?',
  'How many times a day do you brush your teeth?',
  'What is your favorite fast food restaurant? How often do you eat there?',
  'What normally delicious food gets ruined when you wrap it in a tortilla?',
  'Are you an organized person?',
  'Which celebrity is the most likely to have a collection of canes that are just for show?',
  'Would you rather take a one-week $5000 vacation or would you rather go on three different one-week vacations that cost $1700 each?',
  'When you were a child, did you get an allowance? How much was it? Did you have to do chores to earn it? Would you want the same system for your children?',
  'If I could live anywhere in the world, it would be...',
  'What are some clever examples of misdirection you’ve seen?',
  'Do you enjoy camping? What eating/sleeping arrangements are tolerable?',
  'What do you hate most and love most about your car?',
  'What job doesn’t exist now but will exist in the future?',
  'If you and your partner decide to get a hot tub or a pool in the future, who would be responsible for cleaning it?',
  'What’s the most boring super hero you can come up with?',
  'What outdated slang do you use on a regular basis?',
  'Do you have a dream that repeats again and again? What is it?',
  'Where are some unusual places you’ve been?',
  'When was the last time you slept more than nine hours?',
  'What movie or book do you know the most quotes from?',
  'How much does your typical one week vacation cost (not including air fare)? Do you think you take budget vacations, moderate or expensive trips?',
  'Does any particular season make you happier than others? If so, do you know why?',
  'What type of social gatherings do you prefer - small groups or large parties?',
  'If you were a very talented writer and were guaranteed to sell 100,000 copies of whatever book you wrote, what would it be about?',
  'Where do you think you would be most comfortable living? City or country? Near the beach or closer to the mountains? Hot, warm or cold climate?',
  'What TV show character would it be the most fun to change places with for a week?',
  'How did you choose your major in college?',
  'What do you think it means to receive Christ as your Savior and Lord or "have you been saved"?',
  'Do you usually put things back where they belong soon after you use them?',
  'If you were in charge renaming things so that their names would be more accurate, what names would you come up with?',
  'Right now, I’m reading about...',
  'Which meals would you like to be able to eat together? Do you think we will be able to consistently do so?',
  'Do you enjoy eating leftovers? Do you refuse to eat leftovers?',
  'In your present career, how much do you think you will be making in 5 years? 10 years?',
  'If you could choose to know everything about one topic, what area would you choose to be an expert?',
  'What big event do you think will happen soon that most people aren’t expecting?',
  'What’s the most interesting building you’ve ever seen or been in?',
  'Do you allow your pets to be on the furniture?',
  'If you could have any pets you wanted and had the space and money to properly care for them, what pets would you want to have?',
  'Are you good at taking phone messages or passing along important calendar dates to your partner?',
  'What word do you always misspell?',
  'Do you tend to get sea sick or motion sick? What cures have you tried?',
  'What animal or plant do you think should be renamed?',
  'If I could win a lifetime supply of one type of clothing, it would be...',
  'Do you have a favorite bar or place of entertainment? How often do you go there?',
  'What’s the most creative use of emojis you’ve ever seen?',
  'What’s the most annoying noise?',
  'What sport could you play the longest in a televised game, without anyone discovering you aren’t a professional athlete?',
  'Are there any rituals you do every day?',
  'Would you ever spend $100 on a bottle of wine? $300? Under what circumstances?',
  'Would you rather be mute, blind or deaf? Which of the three would be the worst?',
  'Do you have any rooms that are off limits for bringing in food?',
  'If I get to choose my next life, I want to be...',
  'If you were hired to show tourists what life is really like where you live, what would you show them / have them do?',
  'If you were paid a salary to work for any one charity for an entire year, which charity would you choose?',
  'Do you think you are competitive? In what areas?',
  'If you were given a PhD degree, but had no more knowledge of the subject of the degree besides what you have now, what degree would you want to be given to you?',
  "What is your parents' nationality? Were you raised in that culture or do you know much about it?",
  'Would you rather live modestly and retire modestly at 50 or would you rather live more extravagantly and retire modestly at 65?',
  'How long do you usually take to get ready in the morning?',
  'What brand are you most loyal to?',
  'Do you think of yourself more as a leader or a follower?',
  'Where’s the line between soup and cereal?',
  'How often do you go clothes shopping?',
  'How clean do you keep your house?',
  'Are you a morning, a night person or somewhere in the middle?',
  'An epic feast is held in your honor, what’s on the table?',
  'What are your three favorite board/card games?',
  'What current trend do you hope will go on for a long time?',
  'If you were given unlimited resources, how would you lure the worst of humanity into one stadium at the same time?',
  'How many times a day/week do you take a shower or bath? Do you bathe in the morning or night?',
  "Do you think a room full of toys benefits or hinders children's physical and mental development?",
  'Does public speaking frighten you? Have you had much experience with it?',
  'Do you usually just buy what you need at the store, whatever is on sale, or whatever looks good?',
  'If you could have an all-expenses paid trip to see any famous world monument, which monument would you choose?',
  'What form of exercise do you prefer?',
  'To what extend do you think God expects us to follow and obey religious leaders?',
  'Is there anything that you have practically no self-control over (ice cream, offers for a roll in the hay, a bargain shoe sale, a beanie baby for your collection, etc.)?',
  'What piece of “art” would you create if you had to pretend to be an artist and submit something to a gallery?',
  'What’s the longest rabbit hole you’ve been down?',
  'What’s the most overrated product out on the market?',
  'Do you enjoy going to amusement parks? Do you like going on the thrill rides?',
  'Do you put toxic poisons on your yard (weed killer, etc.)? How do you feel about using those chemicals?',
  'Which celebrity do you think is the most down to earth?',
  'Who looks after your home when you are away on vacation?',
  'What’s quickly becoming obsolete?',
  'What actors or actresses play the same character in almost every movie or show they do?',
  'What’s the coolest animal you’ve seen in the wild?',
  'If a fire destroyed your home and all of your belongings, what would you do?',
  'What would be the click-bait titles of some popular movies?',
  'What from the present will withstand the test of time?',
  'What songs do you feel compelled to sing along with when you hear them, even if you don’t totally know all the words?',
  'Have you ever been on a group tour? What do you think about them?',
  "What's your favorite restaurant for casual dining? Favorite special occasion restaurant?",
  'Are you a coupon collector? Do you sometimes get fanatical about saving money on groceries?',
  'Think of a brand, now what would an honest slogan for that brand be?',
  'What inanimate object would be the most annoying if it played loud upbeat music while being used?',
  'How often do you think a bathroom needs to be cleaned? Have you ever cleaned a toilet?',
  'What meal would you eat most often if you could?',
  'Have you ever played any musical instruments? Which ones and do you still play them?',
  'Do you like to take vacations that are activity oriented (cycling trips, skiing trips, scuba trips, etc.)?',
  'What’s the worst movie trope?',
  'If you could hack into any one computer, which computer would you choose?',
  'What current trend makes no sense to you?',
  'If someone narrated your life, who would you want to be the narrator?',
  'My favorite type of art is because...',
  'Which type of home do you think would have the most benefit for our lifestyle? Apartment (no maintenance but not much privacy and not a long term investment)? House (regular yard work and maintenance but the most privacy)? Townhouse/condo (no yard or exterior maintenance but certain restrictions and not as much privacy)?',
  'What was cool when you were young but isn’t cool now?',
  'If there was a book of commandments for the modern world, what would some of the rules be?',
  'Do you usually return phone calls and emails within a day?',
  'If magic was real, what spell would you try to learn first?',
  'Do you have a favorite "fancy" meal?',
  'Have you ever hired a cleaning service? Do you think they are a waste of money or money well spent?',
  'Do you ever pick up hitchhikers? Which type of people would you pick up?',
  'What animal would you most like to eat?',
  "What are your father's and mother's religious backgrounds?",
  'What sort of research, if any, do you do before you travel somewhere?',
  'If you had to be a different nationality, what country would you like to have been born in? Why?',
  'What food have you never eaten but would really like to try?',
  'If I could keep any animal as a pet, I would choose...',
  'If you could take out three things before the blaze, what would they be (Assuming there is no one in the house at the time of the fire.)?',
  'Do you believe in reincarnation?',
  'If cartoon physics suddenly replaced real physics, what are some things you would want to try?',
  'What foods do you really dislike?',
  "What one skill do you wish you had learned but haven't yet (Play the piano? Learn a foreign language? Fly a plane? Etc.)?",
  'If you owned a restaurant, what kind of food would it serve?',
  'Which way should toilet paper hang, over or under?',
  'What product or service is way more expensive than it needs to be?',
  'Which newspapers/newsmagazines do your read? How often? How often do you watch the news?',
  'What sort of tipper are you? Always 15%? Or more or less depending on the service?',
  'Did you complete your taxes from this previous year? Who did them? Do you always file on time?',
  'What movie can you watch over and over without ever getting tired of?',
  'What would be an accurate tag line for each month?',
  'If you enjoy traveling, what places do you like to go to most often? Are there any places you have no desire to go to?',
  'Which, if any, household chores would you expect your children to do? Beginning at what age?',
  'What things about me remind you of anyone from your past, either past sweethearts or good friends?',
  'What sports do you watch on television? College, Pro or both?',
  'If you had a giraffe that you needed to hide, where would you hide it?',
  'Do you usually do some business while you are on vacation (answering email, checking voicemail, returning phone calls, etc.)? How much time each day? Is that pretty much necessary?',
  'When you were a child, what did you want to be when you grew up?',
  'What would be the worst food to be liquefied and drunk through a straw?',
  'What’s something that will always be in fashion, no matter how much time passes?',
  'What’s something that all your friends agree on?',
  'Can you always apply human logic to analyze religion?',
  'What do you think are your optimum hours of sleep to be fully energized?',
  'What’s the most ridiculous animal on the planet?',
  'One of my favorite life hacks is...',
  'Do you have a location in the movie theater where you prefer to sit?',
  'Do you think God created rules and instructions (a religion) to help men keep close to him? Or do you think man just made up those rules?',
  'What temperature do you like it in the house during the winter? Summer?',
  'How do you feel about getting dogs professionally groomed?',
  'What naps are the most satisfying?',
  'Is religion important in your daily life? Why or why not?',
  'How much do you think a person should give to a church or charity? (maybe put in terms of percentage of income)',
  'Do you have a favorite movie? Actor? Actress? Comedy? Drama?',
  'What is the most amazing slow motion video you’ve seen?',
  'What is a talent that you wish you possessed?',
  'How much of your body would you cybernetically enhance if you could?',
  'Do you regularly take vitamins? Do you think the foods you eat have enough naturally occurring vitamins in them?',
  'A TV series I’ve watched all the way through more than once is...',
  'Are you chirpy in the morning or are you a grouch?',
  'Do you wear anything in your hair or on your face when you go to sleep? How about a retainer or orthodontic equipment?',
  'One thing I cannot live without is...',
  'What questions would you like to ask a time traveler from 200 years in the future?',
  'What school sports and activities did you participate in up through college?',
  'If you wanted to slowly drive a roommate insane using only notes, what kind of notes would you leave around the house?',
  'Do you use your yard for any activities?',
  'What two films would you like to combine into one?',
  'Do you write important dates such as birthdays and anniversaries in your calendar? Do you use a calendar? Do you usually remember those dates?',
  'What’s the funniest word in the English language?',
  'Do you feel that the pluses outweigh the minuses regarding having a television in the bedroom? What are the positives and negatives?',
  'Do you currently have a will? If not, why?',
  'How would you feel if your partner wanted to wear matching outfits or dress like you?',
  'How often do you feel the sheets should be changed?',
  'If someone wanted to give you a $50 gift certificate to use on yourself, which store/theatre/spa would you tell him or her you wanted?',
  'Where’s your go to restaurant for amazing food?',
  'What kinds of things do you like to cook or are good at cooking?',
  'If I could have any superpower, it would be...',
  'Do you know most of your neighbors? Do you ever socialize with any of them?',
  "Do you feel like you waste a lot of time? Do you wish you didn't?",
  'Do you prefer a low maintenance yard or a style that demands a bit of work? What style do you like (lots of lawn, lots of flowers, tropical, desert, large vegetable garden, etc.)',
  'What is your favorite ethnic cuisine?',
  'What was the last photo you took?',
  'When you travel, what is your usual goal (relax, sight see, see friends/family, do culture things, eat at new restaurants, etc.)?',
  'How many physical fights have you been in? Do you usually start them? Why do you fight?',
  'What’s the opposite of a koala?',
  'If I had to eat one type of food for the rest of my life, it would be...',
  'Do you have a favorite type (or a couple) of music? A favorite singer? Or musical group?',
  'Do you regularly go to musicals, operas or plays? If not, why?',
  'How many hours a week do you typically devote to your religious practices (e.g. going to church, prayer meetings, bible study, etc.)?',
  'What sort of limitations do you think you would want to place on your children regarding, television, music, magazines, Internet, etc.?',
  'About how many times a month/year do you attend church services?',
  'Do you snore? Can someone hear you snoring from another room?',
  'What’s the funniest thing you’ve seen a kid do?',
  'If I won the lottery, the first thing I’d buy would be...',
  'What sort of plans have you made for retirement?',
  'Do you remember what your favorite childhood books were?',
  'What game have you spent the most hours playing?',
  'What’s the oldest thing you own?',
  'If I had to be trapped in a movie or a video game for a day, it would be...',
  'How does your faith help you cope with problems and trials? Are there evil spirits in the world? Do you fear them? What place do you believe religion will have in our lives?',
  'Have you ever traveled out of the country? Do you have a passport? When does it expire?',
  'What actors or actresses can’t play a different character because they played their most famous character too well?',
  'What do you feel is important in a vehicle for you (seats 5, reliable, good gas mileage, built like a tank, looks good, fast, etc.)?',
  'What food do you crave most often?',
  'What’s the most beautiful beach you’ve been to?',
  'What’s the spiciest thing you’ve ever eaten?',
  'How many movies do you usually watch in a month?',
  'Were you taught proper table manners growing up?',
  'Do you have money invested in the stock market? Do you check your stocks every day? How often do you make trades?',
  'What’s your favorite holiday movie?',
  'How do you handle the language barrier when you travel to foreign countries? Are you willing to visit places where your language might not be spoken?',
  'Do you enjoy going on long road trips as the driver? As the passenger?',
  'What’s your cure for hiccups?',
  'What is the bare minimum you expect in a home?',
  'What shows on television do you always watch?',
  'What animal is the most majestic?',
  "What's your favorite candy bar?",
  'I would love to meet (and even have lunch with)...',
  'Do you go back to the same places again and again or do you desire to go to new places most of the time when you travel?',
  'What smartphone feature would you actually be excited for a company to implement?',
  'If you built a themed hotel, what would the theme be and what would the rooms look like?',
  'Do you think that luck has much to play in your life?',
  'What would be some of the downsides of certain superpowers?',
  'One of my favorite things to do is...',
  'Do you have any allergies?',
  'What bit of trivia do you know that is very interesting but also very useless?',
  'What do you put on your credit cards?',
  'If someone wanted to finance the startup of your business with no strings attached, what business would you start?',
  'Do you like to throw holiday parties or dinners? What do you usually do?',
  'Do you screen phone calls before answering the phone? Can you let the phone ring during meals or when company is over or do you feel compelled to always answer it?',
  'What do you do with your junk mail?',
  'Do you believe that if you give money to churches or charity that you will be financially rewarded? Rewarded in other ways?',
  'Do you usually listen to music around the house? What kind? How loud?',
  'What food is delicious but a pain to eat?',
  'If you could build a vacation home anywhere in the world, where would you build it?',
  'What did you Google last?',
  'What riddles do you know?',
  'What languages do you wish you could speak?',
  'What’s the most comfortable bed or chair you’ve ever been in?',
  'What do you think are my talents? Do you think you have any of the same talents?',
  "Do you like to travel on the spur of the moment (hey, let's drive to the mountains next weekend)?",
  'How to do feel about those who are in different religions? Do you believe that God has a plan to save the whole world from eternal death (those who want to be saved) or only those who hear and believe the "truth" in this lifetime?',
  'Do you usually ask for help or support or do you prefer to fail all on your own?',
  'Do you have a preference for cats or dogs? Indoor pets vs. outdoor pets?',
  'What’s the most boring sport, and what would you do to make it more exciting?',
  // 1
  'What’s the grossest food that you just can’t get enough of?',
  'Do you enjoy doing yard work? Do you expect your partner to help you with the yard work? Or for them to do it without you?',
  'What company do you despise?',
  'Does it bother you if you partner leaves their hair in the sink?',
  'Do you enjoy hosting out of town guests in your home? If so, how long?',
  'When you are old, what do you think children will ask you to tell stories about?',
  'When you are married how many times a week do you think you would eat out?',
  'Have you ever performed on stage in a band, a play or other performance? How did it make you feel?',
  'What do you tend to be humble about? When do you catch yourself being arrogant?',
  'Do you have any strong preferences on naming your children?',
  'Do your religious beliefs prohibit the celebration of certain holidays?',
  'What’s the most ironic thing you’ve seen happen?',
  'Do you believe that God does anything that does not make sense?',
  'What’s the funniest pick up line you’ve heard?',
  'What do you like/dislike about the town(s) where you grew up?',
  'What’s the most recent show you’ve binge watched?',
  'Do you find it easy to start conversations with strangers?',
  'Over the last five years how do you think you have changed for the worse? Better?',
  'When was the last time you stayed up through the entire night?',
  'What’s the smartest thing you’ve seen an animal do?',
  'How comfortable are you speaking in front of large groups of people?',
  'The people I grew up with influenced me by...',
  'How do you make yourself sleep when you can’t seem to get to sleep?',
  'Do you take your pets with you on short trips? Long vacations? Do you put them in a kennel or have a friend watch them?',
  'One thing I know I do well (or better than most) is...',
  'How do you feel about your partner redecorating without consulting you?',
  'What would be the best thing you could reasonably expect to find in a cave?',
  'Do you tend to analyze your decisions before you talk about them or do ideas and thoughts blurt out without much forethought?',
  'Are you more sensitive than most people of your gender?',
  'To what extent are you involved in politics?',
  'Do you eat food that’s past its expiration date if it still smells and looks fine?',
  'Are you allergic to animals? If your fiancé was allergic to your pets, would you be willing to give them away to a good home?',
  'Do you have any special dietary needs? How do you need me to support you with this need?',
  'What’s something that everyone knows is true, but we don’t like to admit it?',
  'What are some things that you consider a waste of time?',
  'Do you believe that the Bible is the inspired Word of God? Why?',
  'Is your business/line of work seasonal? What do you do during the slow periods?',
  'What awful movie do you love?',
  'What’s the funniest actual name you’ve heard of someone having?',
  "What is your opinion on women spending money to get their nails done? Do you have a preference on how you like women's nails?",
  'What outfit could you put together from clothes you own to get the most laughs?',
  'Do you ever diet? What sort of diets do you usually go on?',
  'What’s the most annoying thing about the social media platform you use most often?',
  'What is your favorite type of art? Do you feel you are artistic in any way?',
  'If you had to disappear and start a whole new life, what would you want your new life to look like?',
  'Tear gas makes people cry and laughing gas makes people giggle, what other kinds of gases do you wish existed?',
  'If animals could talk, which animal would be the most annoying?',
  'Instead of the job I have, I’ve always dreamed of being...',
  'What are some of the best vacations you’ve had?',
  'If you suddenly became blind, how would your idea of the perfect partner change?',
  'How would your country change if everyone, regardless of age, could vote?',
  'What life skills are rarely taught but extremely useful?',
  'Do you think that humans will ever be able to live together in harmony?',
  'How do feel about your partner reading your private email?',
  'What movie quotes do you use on a regular basis?',
  "What was the best vacation you've ever taken?",
  'What’s your best story from a wedding?',
  'Men, what do you think is the best thing about being a guy? Women, what do you think is the best thing about being a female?',
  'Who do you think should be responsible for grocery shopping and cooking in a marriage?',
  'What chore do you most detest?',
  'Are there any types of pets that you refuse to live with (snakes, rats, stray dogs, etc.)?',
  'Do you try to eat healthy meals? Organic?',
  'How often do you call in sick when you are not really ill?',
  'If you could talk to animals and they would understand you, but you couldn’t understand them, what would you do with that power?',
  'Is there anything that makes you feel homesick, nostalgic or sentimental?',
  'What country is the strangest?',
  'Do you collect anything? How long have you been collecting? Why do you collect?',
  'What near future predictions do you have?',
  'At what age or what level of financial stability (loans paid off, x dollars in savings) would you like to retire? How do you think you would spend your retirement?',
  'What’s incredibly cheap and you would pay way more for?',
  'In which areas of your life do you feel like you are an independent?',
  'What sort of reaction do you have when you get very upset?',
  'Do you have an idol? Do you try to model yourself after him or her in some way?',
  'If people receive a purple heart for bravery, what would other color hearts represent?',
  'If you lived in a virtual reality world of your own creation, what would it look like?',
  "If you say you are a religious person, do you really practice it? Have you studied your religion's doctrines? In which ways are you not actively following your faith?",
  'Were you always getting in trouble for a particular thing when you were a child?',
  'Are you more of an introvert or an extrovert? Does it change depending on the crowd?',
  'What’s the most awkward thing that happens to you on a regular basis?',
  'If you had huge financial losses and had to liquidate all of your possessions including your car and home, what would that do to your self-esteem?',
  'Do you cook or do you only eat prepackaged food? How often do you go out to eat?',
  'Do you keep things that have no real use and will probably never been used again (old newspapers, magazines, broken appliances, etc.)? Would you be willing to throw out or let your partner help you go through your "junk" if the clutter began to affect your relationship?',
  'My perfect day would start with _____ and end with _____...',
  'What five things have you done in your life that you are most proud of?',
  'What was the best thing that happened to you today?',
  'What would a world populated by clones of you be like?',
  'Who in your life is the worst at using technology?',
  'What always cheers you up when you think about it?',
  "Do you like your last name? If you don't like it, would you consider changing it?",
  'Is it ever appropriate for someone to express anger in a physical way? If so, when and how?',
  'What seemingly innocent question makes you think “It’s a trap!”?',
  'What’s your “Back in my day, we…”?',
  'What was ruined because it became popular?',
  'I know it’s crazy, but I love to eat...',
  'Have you ever given a speech? What was the last one about?',
  'What’s the worst hairstyle you’ve ever had?',
  'What’s something commonly done that gets progressively weirder the more you think about it?',
  'Are you generally an optimist, pessimist or a realist?',
  'If you had a day to yourself with nothing that had to be done, how would you pamper yourself?',
  'What sort of emotions (rage, anger, sorrow, etc.) do you think are inappropriate for people to express publicly?',
  'If you were given the opportunity to successfully run for president, would you do so? When you won, what three things would you most like to improve in your country?',
  'Look in your wallet. How many credit cards do you have? Do you need that many?',
  'Are you able to fall asleep with the lights on? TV on? How do you feel about your partner using your toothbrush?',
  "Do you like to plan your week's menu in advance or cook whatever you are in the mood for (or have ingredients for)?",
  'What has someone borrowed but never given back?',
  'How much money do you have invested or saved (stocks, annuities, retirement funds)?',
  'Do you use foul language? Why do you do it? Does it bother you when you hear others cuss?',
  'What character in a movie could have been great, but the actor they cast didn’t fit the role?',
  "How many hours does it take until you can't stand being alone anymore?",
  'Do you believe that the Satan of the Bible actually exists? If so, what is he doing? Why is he evil?',
  'On average, how many hours do you work in a given week?',
  'On which topics do you feel qualified at giving advice?',
  'Could you ever be married to someone whose breath and clothes always reeked of tobacco?',
  'What’s the most interesting documentary you’ve ever watched?',
  'How often do you call your parents/family members?',
  'What’s your go to casino game?',
  'What did you most enjoy doing with your family when you were a kid?',
  'An accomplishment I’m particularly proud of is...',
  'Do you think you could function without a credit card? Have you ever tried?',
  'What feeling do you have the most difficulty controlling?',
  "Is your current job position where you thought you'd be five years ago?",
  'How often do you pray? Why do you pray?',
  'Are you a balanced person? If so, how did you get to be balanced? If not, what steps do you need to take to be more balanced?',
  'Do you enjoy talking about yourself - your job, your vacations, your accomplishments, etc.?',
  'Am I a nagger? How so? Does it irritate you?',
  'Do you have a role model in your profession? What about them do you admire?',
  'Do you arrive at the airport ahead of time in case problems arise or do you try to get there at the last possible minute so you don’t have to wait?',
  'What is the most important thing you learned from your father? What are some other things he taught you?',
  'What makes you feel important?',
  'Which celebrity or band has the worst fan base?',
  'Do you think you could live more than six hours away from your parents and/or siblings?',
  'What role does art play in your life?',
  'What’s the scariest non-horror movie?',
  'What was the last song you sang along to?',
  'Do you think parents have the right to return (to the store) or give away gifts given to their young children that they feel are inappropriate or junk?',
  'Do you like your first name? Have you ever wished you had a different name? What name would it be?',
  'What are some misconceptions about your hobby?',
  'Do you feel that your partner wastes a lot of time? Does that bother you?',
  'What’s legal now, but probably won’t be in 25 years?',
  "If you don't go to church at all or very often, do you think that might change when you have children? Why wait until then?",
  'How often do you think your gut feeling is correct? When can you remember that it was incorrect?',
  'What do you think about when you hear the word “classy”?',
  'Do you ever lose your temper? How does it manifest itself?',
  "How do you think I handle myself when I'm in a crisis situation?",
  'In which areas are you dependent on others?',
  'If you were given $50,000 to throw a party for all of your friends, what sort of party would you put together?',
  'What artist or band do you always recommend when someone asks for a music recommendation?',
  'If you had a HUD that showed three stats about any person you looked at, what three stats would you want it to show?',
  'What’s the best sandwich you’ve ever had?',
  'I volunteer at. or If I were to volunteer, it would be for...',
  'What is your typical reaction when someone criticizes you? About what things are you most selfish?',
  "After you have used a towel, where do you put it? How often do you feel that towels should be replaced with fresh ones? Would you want to share your partner's towel or have your own?",
  'As a child, what did you think would be awesome about being an adult, but isn’t as awesome as you thought it would be?',
  'How did you feel when a beloved pet of yours died?',
  "Do you have a child's heart sometimes? What sort of “childish” things do you think about doing?",
  'If I could make anything happen for someone, I would...',
  'Do you attend the church you were brought up in? Would you consider attending a different church/denomination if your spouse desired?',
  'Someone once said "A women who does not feel loved needs jewelry, gold and dazzling gifts to be happy. A woman who truly feels loved finds those gifts to be superfluous (nice, but not necessary)". Do you agree?',
  'What are some of the most common misconceptions?',
  'How have you changed since high school? What would your high school pals think about you now?',
  'If I could get paid to blog about anything, I’d write about...',
  'What would the box with all your hopes and dreams inside look like?',
  'When was a time you acted nonchalant but were going crazy inside?',
  'What did you eat so much of that now you hate it?',
  'Do you let your friends drive your vehicle if they need one to run an errand? Would you let you partner drive it on a regular basis?',
  "If you had to take a paid sabbatical and couldn't work for an entire year, what would you most like to do?",
  'When’s censorship warranted?',
  'What profession doesn’t get enough credit or respect?',
  'What movie universe would be the worst to live out your life in?',
  'What really needs to be modernized?',
  'Is it more important that you attend a church where you are comfortable or is it more important that you worship with your husband/children? What do you think of couples who each attend their own Christian church?',
  'What songs do you only know the chorus to?',
  'What’s some insider knowledge that only people in your line of work have?',
  'What do you think is the common link among all (or at least most) of your friends? (School, Work, Personality, Hobbies, etc.)',
  'If you had to be famous, what would you want to be famous for? Do you think fame would be a good thing or a bad thing for your relationship?',
  'Do you prefer receiving expensive gifts or ones that come from the heart?',
  'What two things are terrible when separate but great when you put them together?',
  'Do you generally make to do lists? Would you like it or be offended if your partner helped you make a to do list?',
  'What did you like / dislike about where you grew up?',
  'What’s your best example of easy come, easy go?',
  'Do you think you are interesting or a bore?',
  'How do you feel about pets being in the bedroom or sleeping on your bed?',
  'Have you ever lived alone? Do you or did you enjoy it?',
  'When you are sick and feeling poorly, do you like to be alone or do you like to be pampered and have someone close to your side most of the time?',
  'If I had to leave my native country, I would go to ______ because _____...',
  'Are you content with your current job? If not, why?',
  'Can you live in a place that has junk in the yard (broken down vehicles, old appliances, ratty furniture, etc.)? Does your yard currently have junk in it? What are your plans for the junk? Would you do everyone a favor and haul it to the dump this week?',
  'What’s the funniest TV show you’ve ever seen?',
  'Do you think astrological birth signs represents ones character? Why?',
  'Do you think I am a lot like the other members of my family? How am I like them?',
  'What’s something that everyone, absolutely everyone, in the entire world can agree on?',
  'Do you think that children born today will have better or worse lives than their parents?',
  'What’s your haunted house story?',
  'Do you think life insurance is a wise "investment"?',
  'Do you think of yourself as mechanically inclined?',
  'One thing on my bucket list is...',
  'What are your sleeping habits (do you steal the covers, sprawl all over the bed, etc.)?',
  'What’s the funniest joke you know by heart?',
  'How much time do you currently spend working? What hours do you work? Will that change when you are married and have a family to come home to?',
  'Do you have a "special place"? Why is it so meaningful to you?',
  'Do you go into Internet chat rooms? Are they general chat rooms or devoted to a certain topic?',
  'If the woman in the relationship earns more money than the man how does that make you feel?',
  'What’s the worst thing you ate from a fast food restaurant?',
  'Do you remember your first alcoholic drink? What were the circumstances?',
  'What animal would be the most terrifying if it could speak?',
  'What’s about to get much better?',
  'If you pray, what do you give thanks for and what do you ask for?',
  'Who do you feel like you know even though you’ve never met them?',
  'What is your number one flaw? What steps are you taking to overcome it?',
  'What’s the craziest video you’ve ever seen?',
  'There are many types of love. Can you name some and tell how they are different?',
  'Do you work better alone or with a team? Why?',
  'What is your dream car? Where would you have to be financially to justify the expense?',
  'How many books do you usually read in a year? What type of books do you read?',
  'What are some of the dumbest lyrics you’ve heard in a song?',
  'What do you think could be done to improve the media?',
  'Do you think there are any books or movies I should read or see? Why these?',
  'Which do you think should have the final say in decisions - logic or emotions? Why?',
  'What’s the most annoying animal you’ve encountered?',
  'At what age do you think you would want to let your children group date? Single date? Will you let them go "steady" when they are teenagers?',
  'Do you think you read too much or too little?',
  'What app can you not believe someone hasn’t made yet?',
  'Do you think that you are able to calmly and wisely react in emergencies? What are some examples of emergencies you have had?',
  'Do you prefer to stay in touch with others by letter, email, or the phone?',
  'What are you interested in that most people aren’t?',
  'If you were a ghost and could possess people, what would you make them do?',
  'What would your perfect bar look like?',
  'What’s are some of your Pavlovian responses?',
  'How do you feel about mixing business with family? Business with friends? Do you have any experiences with either scenario?',
  'If you had children, what role would you want the stepparent to play? If you were a stepparent, what role would you like to play?',
  'Would you be willing to go through a workshop or class that discussed the basic beliefs and doctrines of your partner’s church?',
  'Did you go to college? Where? What degree(s) did you get, if any? Do you think your education has paid off? How?',
  'If you could know the truth behind every conspiracy, but you would instantly die if you hinted that you knew the truth, would you want to know?',
  'Do you think that aliens exist?',
  'Do you keep your car clean or do you allow it to pile up with trash first?',
  'When you go on a vacation with someone, do you like doing everything together, most things together or most things on your own and then getting back together for meals?',
  'If you would earn only 70% of your current wages, would you take a job that gave you 100% professional fulfillment?',
  'Do you feed your pets food off of your plate? How do you feel about that practice?',
  'Have you ever gotten a second job to help pay for your non essential purchases?',
  'What’s your best example of fake it till you make it?',
  'Would you want your children to be home schooled? Why or why not?',
  'What qualities do all your friends have in common?',
  'What’s fine in small numbers but terrifying in large numbers?',
  'What’s something that everyone agrees we should change, but somehow it never changes?',
  'What would be the worst thing to hear as you are going under anesthesia before heart surgery?',
  'If someone gave you one million dollars that you were required to give to some person or organization, who would you give it to?',
  "If you didn't receive any gifts for Christmas (or the major holiday you celebrate) how would you feel?",
  'What do a lot of people hope will happen but is just not going to happen?',
  'What sort of parties do you enjoy going to? Do you like to go for a short while or stay until most people have gone?',
  'Were you afraid of God as a child?',
  'What’s the most rage inducing game you’ve ever played?',
  'What’s the most amazing place in nature you’ve been?',
  'What’s the best way you or someone you know has gotten out of a ticket / trouble with the law?',
  'Do you usually have to work on any of the major holidays?',
  'Are you more likely to take over the counter medicines, prescription medicines, homeopathic medicines, natural remedies or nothing at all when you are sick?',
  'What are your thoughts on separate vacations? If we had limited income and different travel priorities, do you think we should take vacations without each other every once in a while?',
  'What is your favorite holiday? Why is it so special to you?',
  'Do you think that dressing is something you do out of necessity or do you enjoy putting outfits together?',
  'What do you think about eating meals (with your family) in front of the television? Do you think family time and discussions around the dinner table are important?',
  'What are your career goals 1, 5 and 20 years from now?',
  'What happens regularly that would horrify a person from 100 years ago?',
  'How soon would you like to move out of our first (or current) home? Next year? Five years? After the kids move out? Never?',
  'Has anyone very dear to you died? How did you handle it?',
  'Do you believe in ghosts, angels or extraterrestrial beings? Why?',
  'What experiences usually make you filled with joy?',
  "Are there any foods you don't eat for health or other reasons?",
  'Do you drink coffee? If so, how many times a week and how many cups each day? Do you feel that you need a caffeine "fix" to get going for the day?',
  'How would you rate your maturity among your peers?',
  "How important to you is a house that is clean and without clutter? Would you be willing to clean the house to your liking if your spouse doesn't clean it to your satisfaction?",
  'Who should be responsible for sending holiday cards and thank you notes from the family?',
  'Do you like it when friends feel comfortable enough to drop by unexpectedly?',
  'How much do you plan / prepare for the future?',
  'What was the most amazing physical feat you’ve managed to pull off?',
  'What was the best job you ever had? Why was it?',
  'What do you envision our home (our realistic home - not our dream home) looking like? The architecture, the décor, the yard, etc?',
  'Are you fearful of germs or food poisoning and tend to toss everything out of the refrigerator that is more than a week old?',
  'Do you think parents should provide cars for their teenagers if they are financially able? Would you allow your teenager to buy his or her own car if he or she had the funds?',
  'What weird food combinations do you really enjoy?',
  'If your great uncle left you $100,000 in his will with the stipulation that you had to invest it for 15 years before you could touch it, what would you do with the money? Be as specific as possible.',
  'What’s the saddest scene in a movie or TV series?',
  'When was the last time you face palmed?',
  'What was one of the most interesting concerts you’ve been to?',
  'Do you tend to buy luxury items or are you frugal with your money?',
  'If you are a Christian, how can you put the focus of the Christmas season on Jesus Christ?',
  'What is your favorite time of day?',
  'What do you do when you hear something fall in the middle of the night while you are in bed?',
  'Do you think your partner can listen to you and do something else (like watch TV or read the paper) at the same time? Can you?',
  'Do you believe all religions are worshipping God the way He wants us to?',
  'Are you camera shy? Why?',
  'Where is the best place you’ve been for taking walks?',
  'What’s the weirdest thing you’ve found lying on the ground / side of the road?',
  'What did you believe for way too long as a child?',
  'What to date has been your greatest source of learning?',
  'If you were married, how would you like to meet new people to socialize with?',
  'What tips or tricks have you picked up from your job / jobs?',
  'What’s your grossest bug story?',
  'Which charity or charitable cause is most deserving of money?',
  'Do you clean up the kitchen after every meal? Each night? Or when you run out of dishes or company is coming over?',
  'Are you highly critical of the food and service when you dine out?',
  'Can you think of any trait of mine that reminds you of your father or mother?',
  'Do you think your family should have a limit on the hours of television watched each day? Would you be willing to start this week?',
  'If you could plan any vacation for us, where would it be?',
  'How often do you balance your checkbook?',
  'What’s better broken than whole?',
  'What are your favorite hobbies? Would you like to spend more time on them?',
  'How many hours a day on average do you spend on the computer/Internet (not counting time spent for work)?',
  'How do you feel when someone close to you disagrees with you?',
  'Something I’d love to get rich by doing full-time is...',
  'What scientific discovery would change the course of humanity overnight if it was discovered?',
  'What elements of pop culture will be forever tied in your mind to your childhood?',
  'What family traditions did you have growing up? Would you want your children to continue them?',
  'How do you usually spend the "big" holidays? Do you do so mainly out of tradition or because you really enjoy celebrating it that way?',
  "How would someone be able to tell if you're happy? If you're sad?",
  'I look up to...',
  'When taking off your clothes, do you immediately put them in the hamper if dirty, hang them up or fold them if clean or leave them on the floor?',
  'Should we try to move to an area that has a really good school system for our children?',
  'Do you expect that both you and your partner would go to bed that the same time each night? How would you feel if your partner wanted to stay up several hours after you went to bed? What time do you usually go to bed on a work night? Non-work night?',
  'Are you one who adapts to change easily? Can you cite some examples?',
  'If your job gave you a surprise three day paid break to rest and recuperate, what would you do with those three days?',
  'What’s the silliest thing you’ve seen someone get upset about?',
  'What trend are you tired of?',
  'What doctrines are essential for a church to teach in order for you to be able to become a member?',
  'What’s your best example of correlation not equaling causation?',
  'Would you want the ability to hear the thoughts of people near you if you couldn’t turn the ability off?',
  'Do you have any superstitions? What are they?',
  'What are the top five qualities that you hope your children will have?',
  "Do you always like to sample your partner's food in restaurants? Does it bother you if someone always wants to taste your food/drink?",
  'What habit do you have now that you wish you started much earlier?',
  'What’s a common experience for many people that you’ve never experienced?',
  'What was the most unsettling film you’ve seen?',
  'How do you think a married couple should celebrate their wedding anniversary? Does it always have to be the same way?',
  'Do you think you would ever have interest in running for a political office?',
  'How important is religion when deciding to seriously date someone? What religious differences would cause you serious doubts about a long-term relationship?',
  'What decisions have you made regarding how you plan to balance work and play?',
  "What's your favorite alcoholic beverage?",
  'If I could download a how-to book directly into my brain, it would be for...',
  'If you are a Christian, what does the word "submission" in Ephesians 5:21,22 mean?',
  "Do you think you would enjoy going on a vacation with your sweetheart's family? Would you detest it or do you not know them well enough to decide?",
  'Do you find it difficult to compromise on things?',
  'Do you live to eat or eat to live?',
  'What goal do you think humanity is not focused enough on achieving?',
  "Prior to this year, what is the best gift you've ever received? Why was it so special?",
  'What’s the creepiest tech out there?',
  'Which protagonist from a book or movie would make the worst roommate?',
  'Which apocalyptic dystopia do you think is most likely?',
  'In what circumstances do you feel most at peace?',
  "Do you enjoy shopping, don't care one way or the other, or detest shopping? Does it change whether it is for clothes, electronics or food?",
  'How much do you spend on wedding gifts? Birthday presents? Christmas gifts?',
  'How important do you think college degrees are in getting a good job? Does the college experience help you to be a successful person in more ways than just the book knowledge?',
  'Would it be okay for your partner to call you at work? Visit you?',
  'What happens in your country regularly that people in most countries would find strange or bizarre?',
  'What movie, picture, or video always makes you laugh no matter how often you watch it?',
  'What’s the weirdest thing about modern life that people just accept as normal?',
  'If money and practicality weren’t a problem, what would be the most interesting way to get around town?',
  'Who in your life has the best / worst luck?',
  'Do you prefer to spend most weekends lazing around the house, getting out of the house or being productive?',
  'Do you like things to be carefully planned or do you prefer to just go with the flow?',
  'Do you fear God? Why or why not?',
  'Where do you get your news?',
  'What’s wrong but sounds right?',
  'Do you have any phobias, fears or concerns about going to the doctor?',
  'In what ways do you feel really blessed?',
  'On a typical day/night out with your friends, what do you do?',
  'What’s something that people think makes them look cool, but actually has the opposite effect?',
  'What fictional characters have you had a crush on over the years?',
  'How ambitious are you?',
  'Have you ever saved for a major expense or purchase or have you always put it on credit?',
  'How much do you think names affect the outcomes of people’s lives?',
  'Do you tend to keep a lot of thoughts and feelings to yourself or do you share them pretty openly?',
  'How would you want to decide on what gifts to purchase for your children?',
  'Do you have problems letting someone else control the remote control? Are you a channel surfer?',
  'What feeling do you have the most difficulty expressing?',
  'If you could live one year of your life all over again without changing a thing, what year would you choose? Why?',
  'What’s the most disgusting sounding word in the English language?',
  'How often do you go to concerts? What kinds? Would you go more often if you had more time/money?',
  'Will you eat everything on your plate no matter how much is there (assuming you like the food)? Or will you quit when you feel full enough? Do you need to feel "stuffed" to be satisfied?',
  'What’s the silliest thing you’ve convinced someone of?',
  'What small change greatly improves a person’s appearance?',
  'What just around the corner tech are you eager to get your hands on?',
  'When we die, what do you think happens to us? What do you base your opinion on?',
  'Do you think that constantly buying your children new toys teaches them to become easily bored with things?',
  'If I could have the world’s best collection of something, it would be...',
  "If you get a pet for your children and they don't take care of it, who will be responsible for cleaning up after it, feeding it and walking it?",
  'Have you read any books on parenting? Do you think it is a good idea to read these books by "experts" or just go by instinct or the advice of family and friends?',
  'Have you tended to date people older or younger than you? Why?',
  'What do you do to protect the environment? Do you think you should do more?',
  'Some people say they are "spiritual" but not "religious". What does that mean to you?',
  'How did you celebrate birthdays as a child? How do you like to celebrate yours now?',
  'When was the last time you got to tell someone “I told you so.”?',
  'Do you support (with money and/or time) any charities or causes?',
  'Do you have a real desire to (or feel that you really need to) get more education? What do you want to study? When do you want to start?',
  'What’s the most historic thing that has happened in your lifetime?',
  'What are you most fearful of? How does that fear keep you from doing things you would like to do?',
  'Can you go out and enjoy a meal or do you always have to "rate" it?',
  'Do you like to be the life of the party or do you prefer intimate, one on one conversation?',
  'What’s the most frustrating product you own?',
  'What physical or personality trait do you think makes people first attracted to you?',
  'How personally involved do you get with "your" team\'s performance? If they lose, does it make you angry or put you in a bad mood?',
  'Ideally, what characteristics would your friends have? What have your friends taught you?',
  'What’s something you really resent paying for?',
  'If you were a clown themed super hero, what powers would you have?',
  'If you and your partner purchased a pet and later split up, how do you think you would decide who got the pet?',
  'Do you have a favorite and least favorite day of the week? Why do you feel that way?',
  'Would you describe yourself as a peace-keeper or a trouble-maker?',
  'What outdoor activity haven’t you tried, but would like to?',
  'After you are married, how much do you expect to spend on clothes each month?',
]
</script>
