name: Label PRs

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  label_pr:
    name: Label PR
    runs-on: ubuntu-latest
    steps:
       uses: actions/labeler@v4.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
